[build]
  command = """
    curl -sSL https://install.python-poetry.org | python3 - &&
    export PATH="/opt/buildhome/.local/bin:$PATH" &&
    poetry config virtualenvs.create false &&
    poetry install --no-dev
  """
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  PATH = "/opt/buildhome/.local/bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = true 