[build]
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt
  """
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  PIPENV_IGNORE_VIRTUALENVS = "1"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = true 